services:
  - type: web
    name: api-health-monitoring
    runtime: static
    repo: https://github.com/amangarg104/API-health-Monitoring.git
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
